name: Vagrant box publish

on: push

jobs:
  box_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Setup Vagrant and Virtualbox
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common vagrant virtualbox
          vagrant --version
          vboxmanage --version
          packer --version
      - name: Build box artifact
        run: |
          make build
      - name: Upload build artifact
        env:
          VAGRANT_TOKEN: ${{ secrets.VAGRANT_TOKEN }}
        if: github.ref  == 'refs/heads/main'
        run: |
          export VERSION="$(date +%y).${{github.run_number}}.${{github.run_attempt}}"
          echo "VERSION=$VERSION"
          make upload
