name: Vagrant Vmware box publish

on:
  push:
  schedule:
    - cron: "1 1 * * *"

jobs:
  box_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Setup Vagrant and Vmware
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget vagrant
          wget -q https://softwareupdate.vmware.com/cds/vmw-desktop/ws/17.5.2/23775571/linux/core/VMware-Workstation-17.5.2-23775571.x86_64.bundle.tar
          tar xf VMware-Workstation-17.5.2-23775571.x86_64.bundle.tar
          sudo bash VMware-Workstation-17.5.2-23775571.x86_64.bundle --console --eulas-agreed --required --set-setting vmware-workstation serialNumber "" --set-setting vmware-player serialNumber "" 
          wget -q https://releases.hashicorp.com/vagrant-vmware-utility/1.0.22/vagrant-vmware-utility_1.0.22-1_amd64.deb
          sudo dpkg -i vagrant-vmware-utility_1.0.22-1_amd64.deb
          sudo systemctl restart vagrant-vmware-utility
          sudo bash -c "cat > /etc/systemd/system/multi-user.target.wants/vagrant-vmware-utility.service" <<EOF
          [Unit]
          Description=Vagrant VMware Utility
          After=network.target

          [Service]
          Type=simple
          ExecStart=/opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility api -config-file=/opt/vagrant-vmware-desktop/config/service.hcl -license-override professional
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target
          EOF
          sudo systemctl daemon-reload
          sudo systemctl restart vagrant-vmware-utility
          vagrant --version
          packer --version
          vmware --version
      - name: Build box artifact
        continue-on-error: true
        run: |
          make build-vmware
      - name: Get logs
        run: |
          find . -name "*.log" -exec cat {} \;
          exit 1
      - name: Upload build artifact
        env:
          VAGRANT_TOKEN: ${{ secrets.VAGRANT_TOKEN }}
        if: github.ref  == 'refs/heads/main'
        run: |
          export VERSION="$(date +%Y%m%d).${{github.run_number}}.${{github.run_attempt}}"
          export PROVIDER="vmware_desktop"
          make upload
