name: Vagrant Vmware box publish

on:
  push:
  schedule:
    - cron: "1 1 * * *"

jobs:
  box_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Setup Vagrant and Vmware
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common vagrant
          wget https://softwareupdate.vmware.com/cds/vmw-desktop/ws/17.5.2/23775571/linux/core/VMware-Workstation-17.5.2-23775571.x86_64.bundle.tar
          tar xvf VMware-Workstation-17.5.2-23775571.x86_64.bundle.tar
          sudo bash VMware-Workstation-17.5.2-23775571.x86_64.bundle --console --eulas-agreed
          vagrant --version
          packer --version
          vmware --version
      - name: Build box artifact
        run: |
          make build-vmware
      - name: Upload build artifact
        env:
          VAGRANT_TOKEN: ${{ secrets.VAGRANT_TOKEN }}
        if: github.ref  == 'refs/heads/main'
        run: |
          export VERSION="$(date +%Y%m%d).${{github.run_number}}.${{github.run_attempt}}"
          export PROVIDER="vmware_desktop"
          make upload
